In [1]:
import torch_geometric

from torch_geometric.datasets import Yelp

dataset = Yelp(root='./OTGNet/process_raw_data/yelp/', transform=None)

dataset

Processing...
Done!


Yelp()

In [3]:
# login to wandb
import wandb
wandb.login()


Failed to detect the name of this notebook, you can set it manually with the WANDB_NOTEBOOK_NAME environment variable to enable code saving.
wandb: Logging into wandb.ai. (Learn how to deploy a W&B server locally: https://wandb.me/wandb-server)
wandb: You can find your API key in your browser here: https://wandb.ai/authorize
wandb: Paste an API key from your profile and hit enter, or press ctrl+c to quit:wandb: Paste an API key from your profile and hit enter, or press ctrl+c to quit:wandb: Appending key for api.wandb.ai to your netrc file: /homes/hliubm/.netrc


True

In [4]:
import wandb
import random

# start a new wandb run to track this script
wandb.init(
    # set the wandb project where this run will be logged
    project="Temporal Graph Continual Learning",

    # track hyperparameters and run metadata
    config={
    "learning_rate": 0.02,
    "architecture": "CNN",
    "dataset": "CIFAR-100",
    "epochs": 10,
    }
)

# simulate training
epochs = 10
offset = random.random() / 5
for epoch in range(2, epochs):
    acc = 1 - 2 ** -epoch - random.random() / epoch - offset
    loss = 2 ** -epoch + random.random() / epoch + offset

    # log metrics to wandb
    wandb.log({"acc": acc, "loss": loss})

# [optional] finish the wandb run, necessary in notebooks
wandb.finish()

wandb: Currently logged in as: hammerlhm. Use `wandb login --relogin` to force relogin


In [1]:
import torch

In [2]:
eye = torch.tril(torch.ones((5, 5))).bool()
eye

tensor([[ True, False, False, False, False],
        [ True,  True, False, False, False],
        [ True,  True,  True, False, False],
        [ True,  True,  True,  True, False],
        [ True,  True,  True,  True,  True]])

In [4]:
pred = torch.tensor([[0, 1, 2, 3, 4], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4]])

temp_eye = eye[2]

pred[:, temp_eye]

tensor([[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]])

In [7]:
a = torch.tensor([1,2,3,4,5,6,7,8,9,10]) + 100
a_idx = torch.tensor([1,2,3,4,5,6,7,8,9,10]) - 1

b = torch.tensor([3,4,5,6,7,8,9,10,1,2]) + 100
b_idx = torch.tensor([3,4,5,6,7,8,9,10,1,2]) - 1

print(b_idx)
b_rev_idx = len(b_idx) - b_idx - 1
print(b_rev_idx)
reverse_idx = torch.arange(len(b_idx) - 1, -1, -1).long()
b[b_rev_idx][reverse_idx]

tensor([2, 3, 4, 5, 6, 7, 8, 9, 0, 1])
tensor([7, 6, 5, 4, 3, 2, 1, 0, 9, 8])


tensor([101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [3]:
a = torch.tensor([1, 2, 3, 4, 5, 6])

mask = (a >= 1) & (a < 3)

a[mask] = a[mask] + 100

a

tensor([101, 102,   3,   4,   5,   6])

In [4]:
import numpy as np
import torch

a = np.array([[1,2,3,4,5], 
             [3,2,1,4,2]])

a = torch.tensor(a, dtype=torch.float32)

l1_reg = torch.abs(a).sum()


l1_reg


# mask = a > 3

# print(mask)
# a[mask]=0
# a

tensor(27.)

In [22]:
import torch

a = torch.tensor([[1,2,3,4,5],
             [3,2,1,4,2]])

a = torch.randn(5, 3)

b = torch.randn(5, 4, 3)

a = a.unsqueeze(1)
print(a.shape)
a = a.repeat(1, 4, 1)
print(a.shape)
# b = torch.tensor([[1,2,3,4,5]])
prd = a * b
# prd = torch.inner(b, a)
print(prd.shape)
print(prd)
sum_prd = torch.sum(prd, dim=2)
sum_prd.shape

torch.Size([5, 1, 3])
torch.Size([5, 4, 3])
torch.Size([5, 4, 3])
tensor([[[-2.0372e-01, -6.6681e-01,  2.4574e+00],
         [ 4.6415e-01,  7.6835e-01, -9.2943e-01],
         [-1.2293e-01,  6.8633e-01, -3.4202e+00],
         [ 6.3812e-01, -3.4149e+00, -1.7023e+00]],

        [[-1.0973e-03, -7.9791e-01,  2.2365e+00],
         [ 2.2072e-01, -3.4932e-01, -1.6873e+00],
         [-5.9466e-02, -1.2966e-02, -2.2481e-01],
         [ 4.3301e-01, -2.2759e-01, -1.1386e+00]],

        [[ 2.2595e-03, -1.3167e+00,  9.5730e-01],
         [-1.1677e-02,  1.7354e-01, -5.5296e-01],
         [ 1.3378e-02, -7.0711e-01,  7.5010e-01],
         [ 2.0156e-02, -1.0380e+00,  5.6850e-01]],

        [[ 1.1295e-01,  2.4097e-01,  5.6424e-03],
         [ 1.0524e-03, -5.0536e-02,  2.9161e-03],
         [ 4.7205e-02, -6.6487e-02,  5.8697e-02],
         [-7.9732e-02, -1.5692e-01,  5.6225e-02]],

        [[-2.7137e-01, -4.4579e-01, -3.2774e-02],
         [-2.3994e-03, -6.8243e-01, -2.1777e-01],
         [ 1.3688e-01, -1.

torch.Size([5, 4])

In [25]:
a = torch.randn(5, 3)

b = torch.randn(5, 3)

(a * b).shape

torch.Size([5, 3])